baseURL = "https://smoliva.blog"
title = "Computer Chronicles Revisited"
theme = "m10c"
paginate = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  author = "S.M. Oliva"
  description = "A review of the PBS series that aired from 1983 to 2002. Written by S.M. Oliva."
  avatar = "/img/cc-pirate.png"
#  avatar = "/img/avatar.jpg"
  favicon = "/img/favicon.ico"
  menu_item_separator = " - "
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:smo@smoliva.com"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/smoliva"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ChronRevisited"
  [[params.social]]
    icon = "rss"
    name = "RSS"
    url = "https://smoliva.blog/index.xml"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
